apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-application
  template:
    metadata:
      labels:
        app: java-application
    spec:
      containers:
        - name: java-application
          image: springlab/petclinic-cicd
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URL
              value: jdbc:postgresql://postgres-db-service:5432/petclinic
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASS
              value: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: java-application-service
spec:
  type: LoadBalancer
  selector:
    app: java-application
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
